version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile:  Dockerfile
    image: jasperphp-app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html/backend
    command: sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache /var/www/html/database && php-fpm"
    ports:
      - "9000:9000"
    networks:
      - jasperphp-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html/backend
      - ./frontend/dist:/var/www/html/frontend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - jasperphp-network

networks:
  jasperphp-network:
    driver: bridge

volumes:
  vendor:
